###########
# site.url, site.title

url:   'http://planetruby.github.io'
title: 'Planet Ruby'

########
# more settings

markdown: kramdown

permalink:  /gems/:title.html

collections:
  links:
    output: true
  apps:
    output: true
  stars:
    output: true

sass:
  sass_dir: css
  style:    expanded


include:
- _data
- _posts

exclude:
- README.md
- _data/books/README.md
- NOTES.md


safe: true
lsi: false

